Removed unnecessary expressions and statements.
molnarmark/fay pull request #2
Opened 2018-05-14 19:00 UTC by Pirulax

2018-05-14 19:09 UTC, molnarmark commented on fay.lua
> +			evaluation = #self.initialValue == right
Indentation doesn't match here.

2018-05-14 19:09 UTC, molnarmark commented on fay.lua
> +			evaluation = #self.initialValue < right
Indentation doesn't match here.

2018-05-14 19:09 UTC, molnarmark requested changes

2018-05-14 19:09 UTC, molnarmark commented on fay.lua
> +			evaluation = #self.initialValue > right
Indentation doesn't match here.

2018-05-15 20:38 UTC, szekelymilan commented
Why do you always try to find bugs / optimization issues in someone else's code? 
**Do something on your own.** :smile:

2018-05-15 21:38 UTC, closed without merging